import {
    Bot, Boxes, Calculator, Eye, FileSpreadsheet, GitBranch, Landmark, Map, Send, ShieldCheck, TrendingUp,
} from 'lucide-react';
import type { CaseStudy, CaseStudyGroup } from '../types';

export const CASE_STUDY_GROUPS: CaseStudyGroup[] = [
    {
        id: 'fieldops',
        eyebrow: '2026 · Field-service ERP platform',
        title: 'One platform, eight systems inside it',
        blurb: 'Built solo for a commercial HVAC & mechanical contractor with roughly 70 field staff and 200 live jobs. Every number below was measured, not asserted; company financials are deliberately left out.',
    },
    {
        id: 'manufacturing',
        eyebrow: '2023–2025 · Manufacturing',
        title: 'Earlier: tools that shipped real parts',
        blurb: 'Production planning and ERP work in MIL-SPEC connector and automotive Tier 1 environments, on Dynamics 365 Business Central and Dynamics AX.',
    },
];

export const CASE_STUDIES: CaseStudy[] = [
    /* ── Field-service ERP platform ── */
    {
        id: 'fieldops-platform',
        group: 'fieldops',
        featured: true,
        icon: Boxes,
        title: 'FieldOps: a field-service ERP, built solo in 17 weeks',
        problem: 'A commercial HVAC & mechanical contractor ran scheduling, cash flow, billing, procurement and HR out of spreadsheets, Smartsheet and hand-assembled bank packages. Its field-service SaaS could not answer the questions the office actually asked.',
        system: 'A custom Frappe/ERPNext application on a single workstation: a DuckDB mirror of the SaaS (1.45M rows across 137 generated doctypes), a refresh engine that proves zero row drift, and 68 desk pages spanning scheduling, finance, procurement, HR, sales, field comms and an AI layer.',
        tools: '364 doctypes, 547 API endpoints, a 12.5k-line planning board, a bank-certificate engine, Telegram bots, Playwright export automation, 204 test scripts.',
        tags: ['Frappe / ERPNext', 'Python', 'DuckDB', 'MariaDB', 'Telegram', 'Ollama'],
        results: [
            '68 pages · 364 doctypes · 227K lines in 17 weeks',
            'Replaced four manual reporting routines and a daily 2.8-hour export chore',
            'Every money figure ties out across pages, to the cent',
        ],
        link: { to: '/fieldops', label: 'Platform deep-dive' },
    },
    {
        id: 'cashflow-backtest',
        group: 'fieldops',
        icon: TrendingUp,
        title: 'Cash-flow forecast, back-tested on 90 jobs',
        problem: 'A 13-week cash forecast whose assumptions nobody had ever checked: when do customers actually pay, and when is a job actually billed?',
        system: 'A back-test harness over a seeded sample of 90 fully-paid jobs from the prior year, comparing forecast issue-to-pay lags and billing timing against what really happened, then feeding the findings straight into the forecast defaults.',
        tools: 'Sampling script, lag statistics, per-customer term overrides, and a "learned lag" feature that was measured and then deleted.',
        tags: ['Python', 'MariaDB', 'DuckDB', 'Forecasting'],
        results: [
            '30-day default terms ran about a week optimistic: median 35 d, mean 46 d',
            '"Learned lag" measured worse than static terms (34 d vs 26 d error) and was removed',
            'Billing-at-completion confirmed: 100% of dollars billed on or before completion',
        ],
    },
    {
        id: 'bbc-twin',
        group: 'fieldops',
        icon: Landmark,
        title: 'Borrowing-base certificate, reproduced cell-for-cell',
        problem: 'Every week someone rebuilt the lender\'s borrowing-base certificate by hand from four QuickBooks exports. Nobody could say whether the numbers were right.',
        system: 'An upload-and-stage import with a tie-out gate, a rules engine for ineligibles (aged, retainage, concentration, contra), and one template that drives both the on-screen tabs and the exported workbook, so the screen is the file.',
        tools: 'A ~2,000-line certificate engine, a cell-for-cell self-test against a filed workbook, snapshot doctypes so any past week reproduces exactly.',
        tags: ['Python', 'openpyxl', 'QuickBooks', 'Finance'],
        results: [
            'All 12 must-match lines reproduce the filed certificate exactly',
            'The contra rule found 5 jobs the hand list had omitted',
            'Flagged an aging line worth 17% of gross A/R with no invoice behind it',
        ],
    },
    {
        id: 'master-schedule',
        group: 'fieldops',
        icon: Map,
        title: 'Master Schedule: planning board, map and routes',
        problem: 'Dispatch lived in the SaaS board and in people\'s heads. Multi-state install tours were planned in Google Maps and email; nobody could see crews, geography and hours together.',
        system: 'One 12,500-line board core mounted by three thin pages (technician gantt, geo map, weekly flow): Leaflet + OSRM road routing, geocoded properties, freehand sketch and annotation layers, saved views, Excel and PNG export, and a write-back that books visits in the SaaS.',
        tools: 'Vanilla-JS desk pages, canvas and SVG renderers, an idempotent two-call visit create, a shared demand engine feeding five surfaces.',
        tags: ['JavaScript', 'Leaflet', 'OSRM', 'Frappe'],
        results: [
            'Three views became three pages with zero backend changes',
            'Route totals (1,746 mi / 31.5 h) matched the manager\'s own maps',
            '85,295 assignment rows censused into one origin taxonomy',
        ],
    },
    {
        id: 'telegram',
        group: 'fieldops',
        icon: Send,
        title: 'Field comms on Telegram, redesigned after a ban',
        problem: 'Per-job chat groups meant hundreds of invite calls a day, which got the company phone number banned. The office still had no progress signal between "dispatched" and "invoice".',
        system: 'One forum supergroup with one topic per job, driven by a Bot API long-poller: a pinned progress card (0–100%, feedback, location), a one-tap "ready to invoice" button, a self-updating labour bar, a morning pace post and a DM hotline.',
        tools: 'Bot API only (all MTProto code deleted), idempotent callbacks that carry target state, a watermarked auto-topic sweep with a runaway guard, a 52-check offline harness.',
        tags: ['Telegram Bot API', 'Python', 'Cron', 'UX'],
        results: [
            'Job-to-topic lag 2.5 h → 5 min via an API poller',
            'Four keyboard markups probed live; the one legal path shipped',
            'Pinned banner redesigned to 27 characters after testing on a phone',
        ],
    },
    {
        id: 'centaurus-guards',
        group: 'fieldops',
        icon: ShieldCheck,
        title: 'Centaurus: an AI that answers from the database and refuses to invent',
        problem: 'An LLM with SQL access will confidently report the entire invoice table as "created today", invent a job address in 718 ms with zero tool calls, or build plausible arithmetic out of field names.',
        system: 'Governed read-only SQL (allowlist, single statement, comment-stripped keyword scan, row cap, timeout, audit log), a finance-column gate that applies anywhere in the statement, mirror-trap guards, a hand-written metric registry, and a fabrication guard that forces a tool call.',
        tools: 'A provider-swappable client (Ollama / Anthropic), tool-spec design, a 31-case adversarial suite, a thinking-spill repair for reasoning models.',
        tags: ['Ollama', 'Anthropic API', 'Python', 'Security'],
        results: [
            '31 adversarial SQL cases, all blocked',
            'Fabrication reproduced 2 of 4 times; 6 of 6 correct after the guard',
            'Silent numeric corruption in 1 reply in 7 found and repaired',
        ],
        link: { to: '/centaurus', label: 'Centaurus page' },
    },
    {
        id: 'estimation-engine',
        group: 'fieldops',
        icon: Calculator,
        title: 'Estimation Engine: labour hours with an honest range',
        problem: 'Estimating labour hours for a new job was experience-only, and the actuals said hours, not rates, were where the money leaked (82% of the labour overrun was hours).',
        system: 'A statistical estimator, deliberately without an LLM: size-normalised nearest neighbours over 1,355 historical quotes, each comparable rescaled by a sublinear power law, a weighted median with P10–P90, shown beside a rule book and a takeoff calculator.',
        tools: 'Calibration harness, three baseline models to beat, per-attribute bonuses, a log of rejected optimisations with their measured cost.',
        tags: ['Python', 'Statistics', 'DuckDB'],
        results: [
            'Median absolute error 37.2% → 35.8% after calibration',
            'P10–P90 range captures 79% of actuals (from 73%)',
            'Beats flat hours-per-dollar, global median and log-log regression',
        ],
    },
    {
        id: 'material-forecast',
        group: 'fieldops',
        icon: Boxes,
        title: 'Material Forecast: a buy board that sees demand before the PO',
        problem: 'The old page only read purchase-order lines, so it saw material after someone had bought it, and it had no time axis at all.',
        system: 'Demand from sold-quote material lines; deadline = sequence start minus a typed lead time; three bands ordered by actionability (needs a date, overdue to order, weeks ahead); start-date and received-ratio rules delegated to the cash-flow module instead of duplicated.',
        tools: 'Conservation tie-outs, a measured decision not to name-match items, honest "unordered balance" rows dated by the longest lead.',
        tags: ['Python', 'Frappe', 'Procurement'],
        results: [
            'Overdue lines 433 → 85 once false alarms were removed',
            'Quote-to-PO item-name overlap measured at 1 in 8, so matching was rejected',
            'Conservation test exact to the cent',
        ],
    },

    /* ── Manufacturing (earlier) ── */
    {
        id: 'centaurus-v1',
        group: 'manufacturing',
        icon: Bot,
        title: 'Centaurus v1: quote automation from customer emails',
        problem: 'Sales engineers spent hours translating free-form customer inquiry emails into structured quotes, re-keying part numbers and prices by hand.',
        system: 'An email-to-quote pipeline: inbox watcher → LLM extraction layer (fine-tuned open-source models, self-hosted) → catalog matching against the ERP → human review gate before anything is sent.',
        tools: 'Model fine-tuning and deployment, extraction prompts, a Business Central catalog matcher, a draft-quote generator.',
        tags: ['LLaMA', 'Python', 'D365 BC', 'On-prem'],
        results: ['Quotes drafted in seconds, not hours', 'Ran in production at a connector manufacturer', 'Humans approve, AI drafts'],
    },
    {
        id: 'po-issuance',
        group: 'manufacturing',
        icon: GitBranch,
        title: 'Automated PO issuance',
        problem: 'Stockouts kept recurring because reorder decisions relied on static reorder points and a weekly manual review of inventory reports.',
        system: 'A replenishment loop around Business Central: inventory monitor → reorder-point engine that accounts for lead-time variability → PO drafting service → planner approval.',
        tools: 'Python monitoring service, lead-time statistics model, BC API integration, SQL reporting.',
        tags: ['Python', 'Business Central API', 'SQL'],
        results: ['Reduced stockouts by 24%', 'Saved 12 hrs/week of manual review'],
    },
    {
        id: 'vision-scraper',
        group: 'manufacturing',
        icon: Eye,
        title: 'Legacy vision scraper',
        problem: 'Shipping data lived inside a 15-year-old AS/400 terminal emulator with no API, no export and no vendor support, re-typed daily by hand.',
        system: 'A desktop vision agent: screen capture → OpenCV template matching to locate fields → OCR extraction → validation rules → clean CSV handoff to the ERP.',
        tools: 'PyAutoGUI navigation scripts, OpenCV matchers, an OCR pipeline, a validation layer.',
        tags: ['OpenCV', 'PyAutoGUI', 'OCR'],
        results: ['100% data accuracy', 'Eliminated manual entry entirely'],
    },
    {
        id: 'inventory-aging',
        group: 'manufacturing',
        icon: FileSpreadsheet,
        title: 'Inventory aging analysis',
        problem: 'Slow-moving capital was invisible: transaction ledgers existed, but nobody could see which inventory had quietly stopped turning.',
        system: 'A SQL data model transforming raw transaction ledgers into aging buckets (0-30, 31-60, 61-90, 90+), refreshed on an automated monthly cadence with finance-ready outputs.',
        tools: 'SQL Server model, bucket classification logic, an automated monthly report.',
        tags: ['SQL Server', 'Data Modeling', 'Finance'],
        results: ['Slow-moving capital surfaced and released', 'Monthly report runs itself'],
    },
];
