/**
 * The proof registry. Every claim the sheet makes lives here with the number behind it.
 * Entries with publishable:false are kept ON PURPOSE so a withheld item cannot be
 * re-added by accident; P() refuses to return them.
 *
 * Rules (fixed): employer, customers, lenders, vendors and staff are never named; no dollar
 * figure from the company's books; no job/quote/invoice numbers; the SaaS is
 * "the field-service SaaS".
 */
export type Area = 'Platform' | 'Scheduling' | 'Finance' | 'Procurement' | 'Centaurus' | 'Field comms' | 'HR' | 'Verification'

export interface Claim {
  id: string
  text: string
  evidence: string
  area: Area
  publishable: boolean
  withholdReason?: string
}

const CLAIMS: Claim[] = [
  /* ---------------- Scheduling ---------------- */
  {
    id: 'sched-one-engine',
    area: 'Scheduling',
    publishable: true,
    text: 'The sequence board and the capacity chart were unified onto one demand engine and one chart renderer after they were found placing identical work in different weeks.',
    evidence: '8 chart bands · 3 shared single sources of truth · what-if implemented as a delta, so “no edits ⇒ identical output” is structural',
  },
  {
    id: 'sched-greedy-colour',
    area: 'Scheduling',
    publishable: true,
    text: 'Board colours are assigned by greedy graph colouring, so no two jobs sharing a week wear the same colour, with minimal churn on re-runs.',
    evidence: 'palette grown 8 → 14 because the busiest week holds 11 jobs · the invariant check must return an empty clash list',
  },
  {
    id: 'sched-timeoff-block',
    area: 'Scheduling',
    publishable: true,
    text: 'Time off is a hard block, not a warning: one authority feeds both scheduling pages, and weekend days inside a run of leave are bridged so a two-week vacation is not half-available.',
    evidence: 'enforced on read and on save · crew fan-out returns a blocked list instead of failing the whole crew',
  },
  {
    id: 'sched-dispatch-conflicts',
    area: 'Scheduling',
    publishable: true,
    text: 'Dispatch-board conflicts are flagged, never auto-corrected, because measuring the overlap showed a blunt “dispatch always wins” rule would erase almost all forward planning.',
    evidence: 'over 14 days: 177 dispatch pairs vs 50 crew pairs, only 4 agreeing · 6 genuine same-day clashes flagged',
  },
  {
    id: 'sched-inspection',
    area: 'Scheduling',
    publishable: true,
    text: 'Inspection days are auto-detected from three simultaneous tests (visit wording, exactly one clocked employee, job type) because the source system records no visit type.',
    evidence: 'a naive one-technician field claimed one tech on 277 job-days and was wrong on 124 of them (45%)',
  },
  {
    id: 'sched-shortfall-viewport',
    area: 'Scheduling',
    publishable: true,
    text: 'A shortfall badge turned out to be a property of the viewport rather than the job: the same job reported a different figure on a 4-week view than on a year view.',
    evidence: '60 of 206 live jobs affected · fixed with an accumulator counted before the window test',
  },
  {
    id: 'sched-worked-history',
    area: 'Scheduling',
    publishable: true,
    text: 'Worked history was backfilled onto the planning board from the timesheet mirror, and the record was given its own key so a record and a plan can share a day.',
    evidence: '116 records across 50 jobs · table 346 → 1,023 rows · 0 rows on the wrong key · 0 plan windows changed',
  },
  {
    id: 'sched-poller',
    area: 'Scheduling',
    publishable: true,
    text: 'New jobs reach the crew’s chat in about five minutes instead of two and a half hours, through a five-minute API poller whose rows are shaped so the later bulk refresh updates them rather than inserting twins.',
    evidence: '~2.5 h → ~5 min · one API call per poll · parity checker across 9 job shapes',
  },
  {
    id: 'sched-visit-write',
    area: 'Scheduling',
    publishable: true,
    text: 'Visit creation from the ERP into the field-service SaaS was proven possible by bisecting a silently-ignoring create schema, then shipped as a two-call flow with the created id committed before the scheduling call, so a retry can never double-create.',
    evidence: '12 candidate field names silently ignored before the working one · no delete route exists, so idempotency was mandatory',
  },
  {
    id: 'sched-route-export',
    area: 'Scheduling',
    publishable: true,
    text: 'The route planner’s Excel export reuses the panel’s own arithmetic (road legs, travel days, arrive and finish dates), so the sheet cannot disagree with the screen.',
    evidence: 'multi-stop road routing with per-leg drive or fly mode · computed dates pushed into the sequence board · a 12,500-line board core wrapped in one module and mounted by three thin pages',
  },

  /* ---------------- Finance ---------------- */
  {
    id: 'cash-backtest',
    area: 'Finance',
    publishable: true,
    text: 'The cash-flow forecast was back-tested against 90 random fully-paid prior-year jobs, and a feature that measured worse than the simple rule was deleted rather than kept.',
    evidence: 'actual median 35 d, mean 46 d against 30-day terms · the learned-lag alternative measured 34 d vs 26 d mean error and was removed',
  },
  {
    id: 'cash-billing-timing',
    area: 'Finance',
    publishable: true,
    text: 'The forecast’s billing-timing assumption was validated against real history and held exactly.',
    evidence: 'median issue-minus-completion gap 0 days · 70% of jobs within ±7 days',
  },
  {
    id: 'cash-committed-gate',
    area: 'Finance',
    publishable: true,
    text: 'Open purchase orders count as committed cash only once their job is dispatched or sequenced, because the team raises orders and parks them until scheduling.',
    evidence: 'previously every open order sat in week zero permanently · parked orders now surface in a non-cash memo row',
  },
  {
    id: 'cert-line-for-line',
    area: 'Finance',
    publishable: true,
    text: 'The compliance-certificate engine reproduces the filed workbook line for line; the rules were reverse-engineered and verified against every affected customer rather than guessed.',
    evidence: 'all 12 must-match lines exact · cross-age verified on all 15 customers · contra reserve reproduces all 27 legacy values',
  },
  {
    id: 'cert-joins',
    area: 'Finance',
    publishable: true,
    text: 'Every join between the imported bank package and the operational mirror was verified rather than assumed, including a suffix rule that closed the last five unmatched invoices.',
    evidence: 'payment key 28/28 · receipt key 156/156 · invoice number 399/404 → 404/404',
  },
  {
    id: 'cert-five-jobs',
    area: 'Finance',
    publishable: true,
    text: 'The generated reserve rule found five jobs a hand-maintained list had omitted, and every downstream line moved by exactly that amount with nothing else changing.',
    evidence: '5 omitted jobs · 4 lines moved by exactly the reserve delta · all other lines identical',
  },
  {
    id: 'cert-four-bugs',
    area: 'Finance',
    publishable: true,
    text: 'Re-baselining the certificate twin against a newer filed workbook exposed four real bugs that had been invisible: a shifted column, a literal hiding behind a formula, a collected-but-never-subtracted deduction, and a changed reserve percentage.',
    evidence: '4 bugs fixed · reader and writer made header-driven so a column shift cannot recur',
  },
  {
    id: 'bank-package',
    area: 'Finance',
    publishable: true,
    text: 'A weekly bank reporting package that used to be assembled by hand is imported, reconciled against the operational system, recomputed and re-exported in the bank’s own four layouts.',
    evidence: '4 workbooks a week · parser self-test on all 10 bucket subtotals plus both grand totals',
  },
  {
    id: 'pace-board',
    area: 'Finance',
    publishable: true,
    text: 'A burn-down board judges each day on its own terms and states the rule, rather than reporting a cumulative line that can call a zero-completion day a success.',
    evidence: 'verdict computed server-side, so finance and non-finance viewers see the same chip · A/B harness proved all 7 KPIs byte-identical',
  },
  {
    id: 'sov-workbook',
    area: 'Finance',
    publishable: true,
    text: 'An AIA-style continuation sheet is rendered as the workbook itself, every border, font, width and merge transcribed from the same template the export writes, so the screen and the download cannot disagree.',
    evidence: '13 columns · 7 sheets · one build feeding both surfaces · a filed application made immutable by stamping its own rates',
  },
  {
    id: 'sov-reseed-trap',
    area: 'Finance',
    publishable: true,
    text: 'A re-seeding trap was caught before it moved money: application cells key on line id, so a forced re-seed would have silently reattached typed amounts to unrelated rows.',
    evidence: 'four cells would have moved onto four unrelated rows and looked normal on screen · safe procedure documented with a dry-run script',
  },
  {
    id: 'sov-glossary',
    area: 'Finance',
    publishable: true,
    text: 'Estimator shorthand on a document a customer pays against is expanded from a glossary built by frequency-counting the real corpus, not invented, with rules that stop an expansion re-matching its own output.',
    evidence: 'glossary built from all 12,163 distinct labour descriptions · a demolition-row rename checked against the corpus first: 4 renamed, 546 correctly kept',
  },
  {
    id: 'jp-decomposition',
    area: 'Finance',
    publishable: true,
    text: 'Cost variance is decomposed exactly into an hours effect and a rate effect, and the decomposition closes to zero residual on every decomposable job.',
    evidence: '0.0 residual on all 315 decomposable jobs (98%) · the remaining 5 carried in an explicit unsplit bucket',
  },
  {
    id: 'jp-hours-drive',
    area: 'Finance',
    publishable: true,
    text: 'The decomposition produced the business finding: hours estimation, not labour rates, drives overrun.',
    evidence: '82% of labour over-run is the hours effect · quoted rate is flat while actuals land in a narrow band',
  },
  {
    id: 'est-range',
    area: 'Finance',
    publishable: true,
    text: 'A statistical labour-hours estimator returns a P10–P90 range and its comparable quotes rather than a point estimate; its accuracy is measured, published on the page, and re-measured after every scoring change.',
    evidence: 'median absolute error 37.2% → 35.8% · within ±25%: 34% → 36% · P10–P90 capture 73% → 79% · 1,355 size-matchable quotes',
  },
  {
    id: 'est-baselines',
    area: 'Finance',
    publishable: true,
    text: 'It beats every simpler baseline it was tested against, and the alternatives are recorded so nobody re-proposes them.',
    evidence: '37.2% median error vs flat hours-per-dollar 55% · global median 74% · log-log regression 45%',
  },
  {
    id: 'est-no-llm',
    area: 'Finance',
    publishable: true,
    text: 'It deliberately uses no language model: size-normalised nearest neighbours, each comparable rescaled by a sublinear power law, and a weighted median.',
    evidence: 'confidence graded on neighbour spread, because attribute-match count measured non-monotonic against error',
  },
  {
    id: 'collections',
    area: 'Finance',
    publishable: true,
    text: 'An A/R collections worklist scores every customer 0–100 on named, tooltip-exposed weights and pushes a promise-to-pay straight into the cash-flow forecast.',
    evidence: 'size 35 · age 25 · broken promise 15 · overdue action 10 · stale 10 · blocker 5 · open promise −15 · per-invoice tie-out proven both ways',
  },
  {
    id: 'entry-screens',
    area: 'Finance',
    publishable: true,
    text: 'Five accounting entry screens were built only after measuring which documents are still typed natively rather than arriving from the field system.',
    evidence: '~8,900 documents a year: checks 3,400 · card bill payments 2,964 · check bill payments 976 · transfers 528 · deposits 427 · card charges 348 · journals 226',
  },
  {
    id: 'commission',
    area: 'Finance',
    publishable: true,
    text: 'A per-salesperson commission statement replaced a hand-kept workbook and was reconciled against it before being trusted.',
    evidence: 'draw schedule an exact match · one quarter’s bookings an exact match · earlier quarters within 3–5%, with the differences explained by source dating',
  },
  {
    id: 'closed-status',
    area: 'Finance',
    publishable: true,
    text: 'A retired invoice status was correctly split into “billed revenue” but “not collectible A/R”; one line of code carries the whole policy, and the safety argument is that the A/R side is provably unchanged.',
    evidence: '2,883 invoices affected · cross-checks over 5,598 jobs, 0 mismatches both ways · two report responses byte-identical before and after',
  },

  /* ---------------- Procurement & estimating ---------------- */
  {
    id: 'buy-board',
    area: 'Procurement',
    publishable: true,
    text: 'The material forecast was rewritten from a page that could only see material after it had been bought into a weekly buy board driven by sold-quote demand and a per-line lead time.',
    evidence: 'three bands: needs a date · overdue to order · weekly · conservation test ties to the cent',
  },
  {
    id: 'buy-board-defects',
    area: 'Procurement',
    publishable: true,
    text: 'Three defects in the new buy board were caught by tie-outs before anyone used it, including one that produced hundreds of false “late” alerts.',
    evidence: 'overdue band 433 → 85 lines once on-order work stopped being called late · 566 → 527 rows with 0 duplicate keys',
  },
  {
    id: 'buy-no-match',
    area: 'Procurement',
    publishable: true,
    text: 'The board refuses to guess which item is unbought when a job already has purchase orders, because quote and purchase vocabularies were measured to barely overlap.',
    evidence: '1 of 8 quote item names on the sample job matched any purchase-order item name',
  },
  {
    id: 'trackers-upsert',
    area: 'Procurement',
    publishable: true,
    text: 'Two spreadsheet trackers became first-class pages with an upsert contract, so a row edited in the app survives the next import instead of being overwritten.',
    evidence: 'deduplicating key verified unique · only genuinely changed fields are pinned, so one dialog save cannot freeze a row',
  },
  {
    id: 'po-mirror',
    area: 'Procurement',
    publishable: true,
    text: 'The purchase-order mirror was repaired after every one of roughly 27,000 orders was found sitting as an unsubmitted draft with zero totals and every line orphaned, which is why every buying report read empty.',
    evidence: 'a parent relink rewritten from a correlated subquery to a plain indexed update: 10+ minutes → ~10 s',
  },
  {
    id: 'takeoff',
    area: 'Procurement',
    publishable: true,
    text: 'An estimator’s local takeoff script was ported into the ERP and validated cell-exact against the workbook a colleague had already delivered.',
    evidence: '0 diffs across all 5 sheets, including formulas, merges and the download filename',
  },

  /* ---------------- Field comms ---------------- */
  {
    id: 'crew-forum',
    area: 'Field comms',
    publishable: true,
    text: 'Crew messaging was re-architected from per-job groups to one forum with a topic per job, after the old design’s invite volume matched the canonical spam signature and got an account banned.',
    evidence: '~560 invites + ~50 contact imports a day under the old design · topic creation is one call that adds nobody and imports nothing',
  },
  {
    id: 'crew-pinned-card',
    area: 'Field comms',
    publishable: true,
    text: 'The pinned per-job progress card was sized against a real phone rather than a character budget, because the pinned banner shows one clipped line.',
    evidence: 'worst case reduced to 27 characters · bar cells set to 8 after 10 was rejected on a phone · a 7-check shape suite guards it',
  },
  {
    id: 'crew-hammer-down',
    area: 'Field comms',
    publishable: true,
    text: 'One tap tells the office a job is good to invoice, finished or not; the callback carries the target state so a replayed batch is harmless, and an audit row is written in both directions.',
    evidence: '52 offline checks · the confirmation step was removed because the undo IS the safety and a wrong tap costs one tap',
  },
  {
    id: 'crew-hour-corrections',
    area: 'Field comms',
    publishable: true,
    text: 'Technicians correct their clocked timeline row by row from a chat message; an initial total-only version was rejected because a total says the answer is wrong without saying which row to fix.',
    evidence: 'reproduces the source system’s own edit dialog row for row · 65 harness checks · advisory only, the office re-keys',
  },
  {
    id: 'crew-bilingual',
    area: 'Field comms',
    publishable: true,
    text: 'Field direct messages are bilingual, with one module owning every canned string, an explicit resolution order, and a prompt rule keeping tool search terms in English because the policy corpus is English.',
    evidence: 'explicit choice › detection of the current message › phone language › English · detection requires two markers · 65 offline checks',
  },
  {
    id: 'crew-dedupe-key',
    area: 'Field comms',
    publishable: true,
    text: 'Every field write carries a unique deduplication key because the message poller commits its cursor per batch: an absolute set replays harmlessly, a relative change would apply twice.',
    evidence: 'two key shapes (tap and command) · the replay case has its own regression test',
  },
  {
    id: 'crew-location-button',
    area: 'Field comms',
    publishable: true,
    text: 'A one-tap location button was proven impossible inside a group topic by probing the live bot API with four markup variants, then replaced with a deep link into the private chat where the request is legal.',
    evidence: '4 probes · 3 explicit refusals · 1 working alternative · the request is one-shot and expires in 30 minutes',
  },
  {
    id: 'crew-location-declined',
    area: 'Field comms',
    publishable: true,
    text: 'Passive location tracking was costed, measured and declined; the measurement showed the existing clock-punch GPS is already good enough for most of the fleet.',
    evidence: '103,645 fixes · over 45 days 56% within 100 m and 70% within 2 km of the job property',
  },
  {
    id: 'crew-photo-summaries',
    area: 'Field comms',
    publishable: true,
    text: 'Per-job AI summaries fuse photo insights with crew chat, so a job with zero analysed photos still produces a real summary.',
    evidence: 'all 20 top jobs produced summaries · 5 of them from chat alone',
  },
  {
    id: 'crew-labor-bar',
    area: 'Field comms',
    publishable: true,
    text: 'A missing progress bar on unquoted jobs was documented as correct behaviour, with the ratio measured, rather than debugged as a broken sync.',
    evidence: 'estate-wide, 271 of 477 jobs worked in 90 days had no quoted hours',
  },
  {
    id: 'crew-pace-post',
    area: 'Field comms',
    publishable: true,
    text: 'The morning pace post into the crew’s general channel reads the same payload as the board, so the group and the dashboard can never disagree; money is deliberately stripped because the channel is a wider audience than the page’s gate.',
    evidence: 'weekday cron · money keys popped before posting · two independent off switches',
  },
  {
    id: 'crew-auto-topics',
    area: 'Field comms',
    publishable: true,
    text: 'Automatic topic creation is watermarked so switching it on starts from that moment, with a runaway guard that refuses and switches itself off, verified live rather than trusted.',
    evidence: 'guard refuses above 60 candidates · at a zero watermark it saw 406 candidates and made zero API calls',
  },

  /* ---------------- Centaurus ---------------- */
  {
    id: 'cai-governed-sql',
    area: 'Centaurus',
    publishable: true,
    text: 'The AI layer writes its own SQL against the operational database, behind entirely server-side guards.',
    evidence: 'SELECT/WITH only · single statement · comments and literals blanked before the keyword scan · 39-table allowlist · 200-row cap · 15 s statement timeout · every attempt logged',
  },
  {
    id: 'cai-adversarial',
    area: 'Centaurus',
    publishable: true,
    text: 'The SQL guard is proven by an adversarial suite covering writes, stacked statements, comment-hidden payloads, file exports, session variables, unlisted tables and pay columns in both SELECT and WHERE.',
    evidence: '31 cases, re-run after every guard change · a standing failure is treated as how a real regression hides',
  },
  {
    id: 'cai-redaction',
    area: 'Centaurus',
    publishable: true,
    text: 'Column-level redaction is applied to what the database returned, not to the query text, because that is the only place a wildcard select has already been expanded; dropped columns are named back to the model.',
    evidence: 'three star-select cases added to the guard suite to cover it',
  },
  {
    id: 'cai-creation-stamp',
    area: 'Centaurus',
    publishable: true,
    text: 'A whole class of confident wrong answer was guarded in the data layer rather than the prompt: most mirror tables carry the sync time in their creation column, so “what did we create today” returned the entire table.',
    evidence: '30 of the readable mirror tables affected · a natural question would have reported 7,440 invoices as today’s work instead of 2',
  },
  {
    id: 'cai-metric-registry',
    area: 'Centaurus',
    publishable: true,
    text: '“How is this figure calculated” can only be answered from a hand-written registry whose entries carry code anchors that self-test; a miss returns “I don’t know” instead of a plausible guess.',
    evidence: '35 entries, 9 with value queries · asked about one figure, the model had previously offered three ranked guesses, all wrong',
  },
  {
    id: 'cai-vocabulary',
    area: 'Centaurus',
    publishable: true,
    text: 'The registry also carries in-house vocabulary, after an abbreviation holding hours was silently answered as a dollar figure.',
    evidence: 'scoring rewritten to word-run containment so an exact match settles it',
  },
  {
    id: 'cai-fabrication',
    area: 'Centaurus',
    publishable: true,
    text: 'A fabrication guard was added after a live wrong answer was shown to be reproducible, not an anomaly: the server now requires a lookup for data-shaped questions and refuses rather than guesses.',
    evidence: 'reproduced 2 times in 4 on replay · one forced retry, then a refusal · discarded text retained under an explicit guard label so the rate is measurable',
  },
  {
    id: 'cai-blank-answers',
    area: 'Centaurus',
    publishable: true,
    text: 'Intermittent blank answers were root-caused to a reasoning model spending its entire turn thinking inside a shared token budget, and fixed with a per-turn floor and a guaranteed non-empty exit path.',
    evidence: '1,300–1,600 output tokens spent thinking against a 2,048 budget · per-turn floor 8,000 · tool rounds 6 → 8',
  },
  {
    id: 'cai-thinking-spill',
    area: 'Centaurus',
    publishable: true,
    text: 'A silent numeric-corruption bug in the model transport was found and repaired: roughly one reply in seven lost the opening characters of the answer into the thinking field, turning a figure into a smaller one.',
    evidence: '4 of 15 replies mangled untreated · repair guarded by four conditions · 14 offline unit cases',
  },
  {
    id: 'cai-audit-log',
    area: 'Centaurus',
    publishable: true,
    text: 'An audit trail that had never written a single line was found and fixed: the logger was pinned at error level on a production bench, so every entry was discarded.',
    evidence: 'both log files at 0 bytes since creation · lesson recorded: do not read an empty app log as “the feature never ran”',
  },
  {
    id: 'cai-join-keys',
    area: 'Centaurus',
    publishable: true,
    text: 'Join keys were published to the model as structured metadata after the commonest generated-query failure turned out to be assuming a parent–child relationship that does not exist in flat mirror tables.',
    evidence: 'documented key pairs · both failing questions then answered correctly on the first query instead of 5+ refused attempts',
  },
  {
    id: 'cai-materiality',
    area: 'Centaurus',
    publishable: true,
    text: 'An AI review queue that had stopped being read was fixed by separating two questions, “can the evidence support this?” and “is it worth interrupting anyone?”, and reporting them separately all the way to the run log.',
    evidence: 'queue 116 → 37 open items · profiles measured against the live queue: Light 89 kept · Moderate 70 · Aggressive 37',
  },
  {
    id: 'cai-same-profile',
    area: 'Centaurus',
    publishable: true,
    text: 'The prompt and the gate read the same materiality profile, so the model is never told one threshold while the validator enforces another.',
    evidence: 'thresholds injected by token replacement, because the prose contains literal percent signs · re-scoring is dismiss-with-reason, never delete',
  },
  {
    id: 'cai-governance-1',
    area: 'Centaurus',
    publishable: true,
    text: 'A full AI governance review ran over every open job with crew activity in a two-week window, with zero fabricated citations.',
    evidence: '145 open jobs · 127 needing analysis over 11 shards (1.2 MB of transcript) · 15 items proposed → 14 kept · queue 60 → 52',
  },
  {
    id: 'cai-governance-2',
    area: 'Centaurus',
    publishable: true,
    text: 'The second review ran incrementally, scoped by content hash, so unchanged work was not re-reasoned.',
    evidence: '55 job-days re-analysed instead of all 132 jobs · 7 proposed → 6 loaded, 0 rejected, 0 filtered',
  },
  {
    id: 'cai-offline-track',
    area: 'Centaurus',
    publishable: true,
    text: 'An offline reasoning track lets a stronger model do the thinking while the export and load paths never call a model, and every cited quote is verified verbatim against the exported transcript before loading.',
    evidence: 'the verifier checks the key diff and quote-for-quote fidelity · a dry-run validation and materiality pass runs before every load',
  },
  {
    id: 'cai-navigation',
    area: 'Centaurus',
    publishable: true,
    text: '“How do I get to X” is answered with click steps derived live from the workspace records plus a cached screenshot with the tile ringed: steps live, pixels cached, because labels drift.',
    evidence: '22 navigation screenshots · 67 labelled click targets · a keying defect affecting 4 pages fixed to 0 of 62',
  },
  {
    id: 'cai-navshot-tool',
    area: 'Centaurus',
    publishable: true,
    text: 'The screenshot was moved out of the model’s hands after it produced correct steps and simply omitted the image: a prompt instruction is a request, not a guarantee.',
    evidence: 'the attachment is rendered from the tool result, with duplicate suppression and a permission-restricted skip path · covered by a jsdom test on the shipped functions',
  },
  {
    id: 'cai-model-verified',
    area: 'Centaurus',
    publishable: true,
    text: 'Model deployment is verified per capability, not assumed: plain chat, native tool calling through the real query loop, and vision through the real photo path were each exercised live before the switch.',
    evidence: 'chat 3.6 s · a live tool-calling query returning the correct job count · vision 4.9 s on a real site photo against 18 s on the previous vision model',
  },
  {
    id: 'cai-local-vs-hosted',
    area: 'Centaurus',
    publishable: true,
    text: 'Local versus hosted inference was measured rather than argued.',
    evidence: 'the same photo: 156 s and 22 GB of resident memory locally, 18 s and no local memory hosted',
  },
  {
    id: 'cai-photo-backfill',
    area: 'Centaurus',
    publishable: true,
    text: 'A photo-description backfill produced tens of thousands of structured insights over hundreds of sharded batches, with a verifier that diffs the task against the result because a self-reported “complete” is not proof.',
    evidence: '32,921 rows · 0 failed · 700+ shards · concurrency tuned down to 8–9 workers after a 20-worker wave tripped rate limits',
  },
  {
    id: 'cai-hotline',
    area: 'Centaurus',
    publishable: true,
    text: 'Direct messages from staff are answered by the same layer as an HR and office assistant, with identity-bound tools: the employee id is a closure, never a model argument, and technicians get no SQL.',
    evidence: '6 read-only tools · 12 for technicians · 18 for office and HR · escalation guaranteed server-side when the policy corpus has no answer',
  },
  {
    id: 'cai-directory',
    area: 'Centaurus',
    publishable: true,
    text: 'A directory of who handles what was built as a deliberately PII-free table so it can be exposed to ad-hoc queries, with a routing key weighted above prose and a negative weight for “do not contact for”.',
    evidence: 'negative weight −4 stops the longest profile absorbing every query · one tool answers both “who handles X” and “what does this person do”',
  },

  /* ---------------- HR ---------------- */
  {
    id: 'hr-calendar',
    area: 'HR',
    publishable: true,
    text: 'An HR month board was built with zero new doctypes: it is a view over four existing sources, and the overlay subtracts so approved leave is never painted twice.',
    evidence: '4 sources · 1 schema change (3 fields on an existing table) · the true invariant found by a test that correctly failed the first, naive one',
  },
  {
    id: 'hr-leave-categories',
    area: 'HR',
    publishable: true,
    text: 'Leave categories are derived from the office’s own transcription rather than parsed from the scanned form, because sampling showed the form parse contradicts the office in a third of readable cases.',
    evidence: 'of 60 sampled forms only 22 yielded a machine-readable mark, and 8 of those contradicted the transcription · the text classifier then classified 411 of 429 records',
  },
  {
    id: 'hr-chip-colours',
    area: 'HR',
    publishable: true,
    text: 'Chip colours were chosen numerically rather than by taste, ranked by perceptual distance so the two commonest categories cannot be confused.',
    evidence: 'the two commonest sat 24.7 ΔE apart · the chosen colour scores 68.0 ΔE against its neighbour and a minimum 29.7 ΔE against all 16 others',
  },
  {
    id: 'hr-paperwork',
    area: 'HR',
    publishable: true,
    text: 'The paperwork feature was rebuilt after its founding premise proved wrong: none of the files attached to the leave records were forms; the signed documents live on timesheet notes.',
    evidence: '429 leave documents (393 PDFs) found on timesheet notes · one month went 3 files → 57',
  },

  /* ---------------- Verification ---------------- */
  {
    id: 'ver-tieouts',
    area: 'Verification',
    publishable: true,
    text: 'Cross-page tie-outs are the regression tests: every new financial surface must reproduce the page that already owns the number, per job, before it ships.',
    evidence: 'five surfaces agree across 5,598 jobs with 0 mismatches · a lookup page verified at 1,651 values over 127 jobs, 0 mismatches · an invoice review tied to progress billing over 262 rows, 0 mismatches',
  },
  {
    id: 'ver-fingerprint',
    area: 'Verification',
    publishable: true,
    text: 'Workbook-rendering pages are fingerprinted cell by cell (value, style, height and merge) against a pinned baseline, so any drift is attributable to exactly one document.',
    evidence: '22 workbooks in the baseline · baseline v4 → v8 over three days, every bump attributable to a single job',
  },
  {
    id: 'ver-jsdom',
    area: 'Verification',
    publishable: true,
    text: 'A jsdom harness executes the page’s real shipped JavaScript and records exceptions that a browser silently swallows inside promise callbacks: the class of bug that makes a button “do nothing” with a clean console.',
    evidence: 'three harnesses · caught three fatal-on-load temporal-dead-zone bugs on three different pages, three for three',
  },
  {
    id: 'ver-noop',
    area: 'Verification',
    publishable: true,
    text: 'A demand-engine change was proven a no-op before it shipped by taking a deterministic snapshot on the same data before and after, then moving one deliberate override to show it changed exactly the expected amount.',
    evidence: 'before: 13 periods × 202 jobs · after: 13 periods × 202 jobs · diff: 0 cells · one per-day override → +24 h, nothing else moved',
  },
  {
    id: 'ver-snapshot-revert',
    area: 'Verification',
    publishable: true,
    text: 'A snapshot / diff / revert procedure exists specifically because the source mirror refreshes every two hours: a control snapshot taken across a refresh shows phantom differences.',
    evidence: '3 scripts, so the control is taken on the same mirror generation',
  },
  {
    id: 'ver-browser-measure',
    area: 'Verification',
    publishable: true,
    text: 'Animation and layout behaviour is measured in a real browser rather than eyeballed, with probes that run against the previous file and the new one for a true before / after.',
    evidence: 'a responsiveness fix measured as median 655 → 100 px/s · 34 → 4 jerky frames · 6,946 → 1,252 px of travel per 12 s',
  },
  {
    id: 'ver-backup-audit',
    area: 'Verification',
    publishable: true,
    text: 'Backup coverage was audited rather than assumed: the whole-database dump was diffed against the live schema and every custom table, view and sequence was present.',
    evidence: '1,168 / 1,169 base tables · 53 views · 5 sequences · 82 analytics tables mapping 1:1 with 0 row drift',
  },
  {
    id: 'ver-concurrent-edits',
    area: 'Verification',
    publishable: true,
    text: 'Several engineering sessions edited the same codebase concurrently, so every change was made by a read-modify-write patch script with an asserted anchor and a diff against a fresh backup.',
    evidence: 'an encoding corruption of 455 box-drawing characters, 50 dashes and 6 ellipses survived four green test runs and was caught only by diff',
  },
  {
    id: 'ver-harness-crash',
    area: 'Verification',
    publishable: true,
    text: 'A harness was hardened to survive its own crash after one exception in a timer callback made 47 passing assertions read as total failure.',
    evidence: 'an uncaught-exception handler now records the crash as a failure and prints what it has',
  },
  {
    id: 'ver-column-engine',
    area: 'Verification',
    publishable: true,
    text: 'A shared column-layout engine was verified in a real logged-in browser across four report pages, including that a custom-column export still ties to the full export to the cent.',
    evidence: 'head, body and foot cell counts equal on all four pages · layout survives reload · a 3-column export ties exactly',
  },
  {
    id: 'ver-scheduler-ast',
    area: 'Verification',
    publishable: true,
    text: 'A duplicate-key defect in the scheduler config was found by parsing the source as an AST: one cron spec silently discarded another, so a job had never been registered at all.',
    evidence: '1 shadowed job, detected by parse rather than by reading',
  },
  {
    id: 'ver-hygiene',
    area: 'Verification',
    publishable: true,
    text: 'An application-wide hygiene review cut mirror-refresh index churn to zero and pruned the version log by 87%, with every removed file archived first.',
    evidence: '~397 redundant DDL statements per 2-hour cycle → 0 · 104,115 → 13,509 rows · 331 stale backup files archived · 26 loop-closure defects fixed',
  },

  /* ---------------- rejected and recorded ---------------- */
  {
    id: 'rej-learned-lag',
    area: 'Verification',
    publishable: true,
    text: 'Learned payment lag, rejected.',
    evidence: 'mean error 34 d vs 26 d for the plain terms rule · removed',
  },
  {
    id: 'rej-item-match',
    area: 'Verification',
    publishable: true,
    text: 'Item-name matching between quotes and purchase orders, rejected.',
    evidence: '1 in 8 overlap on the sample job · the board reports an unordered balance instead',
  },
  {
    id: 'rej-won-only',
    area: 'Verification',
    publishable: true,
    text: 'A won-only comparables pool for the estimator, rejected.',
    evidence: '44–47% median error vs 41% for the full pool',
  },
  {
    id: 'rej-material-cost',
    area: 'Verification',
    publishable: true,
    text: 'Material cost as an estimator predictor, rejected as leakage.',
    evidence: 'correlates 0.92 with hours but is a quote output · bridged variant 45.2% vs 40.8% median error',
  },

  /* ---------------- Platform ---------------- */
  {
    id: 'plat-export-repair',
    area: 'Platform',
    publishable: true,
    text: 'The two-hourly export automation was repaired without vendor cooperation after an endpoint-security hook began crashing the browser at download start: the finished workbook is read out of the page as an in-memory object instead.',
    evidence: '13 consecutive failures diagnosed to an in-process hook · 345 MB read out in 42 chunks in 52 s · byte-exactness proven with a checksum harness before the first live run',
  },
  {
    id: 'plat-columns-adopt',
    area: 'Platform',
    publishable: true,
    text: 'A contract-driven mirror silently drops columns added upstream, so a re-runnable adoption tool plus a warning in the refresh log were built rather than relying on someone noticing.',
    evidence: '45 new columns across 13 sheets adopted in one run · additive by design, so it never wipes hand-set metadata',
  },
  {
    id: 'plat-backups',
    area: 'Platform',
    publishable: true,
    text: 'Two independent backup tracks run unattended: data every six hours with rotation and a watchdog, source code plus a full git bundle every two days.',
    evidence: '15 off-site code sets retained · ~11 s per code run',
  },

  /* ---------------- WITHHELD (publishable: false — never rendered) ---------------- */
  {
    id: 'wh-backlog-capacity',
    area: 'Scheduling',
    publishable: false,
    withholdReason: 'hours × any trade rate is revenue; backlog-vs-capacity is the commercially sensitive figure',
    text: 'Booked backlog measured against crew capacity.',
    evidence: 'withheld',
  },
  {
    id: 'wh-seven-figures',
    area: 'Centaurus',
    publishable: false,
    withholdReason: 'a dollar magnitude for a single job, and by implication a single customer',
    text: 'One job carried zero in the source billed field against seven figures of issued invoices.',
    evidence: 'withheld',
  },
  {
    id: 'wh-1099',
    area: 'Finance',
    publishable: false,
    withholdReason: 'compliance exposure of an identifiable employer',
    text: 'Supplier payments by card, suppliers missing a tax id.',
    evidence: 'withheld',
  },
  {
    id: 'wh-security',
    area: 'Platform',
    publishable: false,
    withholdReason: 'live security posture of a production system',
    text: 'The number and content of security-review findings.',
    evidence: 'withheld',
  },
  {
    id: 'wh-egress',
    area: 'Centaurus',
    publishable: false,
    withholdReason: 'a data-governance disclosure about someone else’s company',
    text: 'The configured model tag was a proxy stub, so data left the premises.',
    evidence: 'withheld',
  },
  {
    id: 'wh-headcount',
    area: 'HR',
    publishable: false,
    withholdReason: 'staffing detail about an identifiable employer',
    text: 'Login-to-payroll reconciliation counts.',
    evidence: 'withheld',
  },
  {
    id: 'wh-customers',
    area: 'Scheduling',
    publishable: false,
    withholdReason: 'narrows the anonymized employer to one company',
    text: 'Active customer and city counts.',
    evidence: 'withheld',
  },
  {
    id: 'wh-endpoints',
    area: 'Centaurus',
    publishable: false,
    withholdReason: 'security defect detail on a live system',
    text: 'Endpoints found without a gate and re-gated.',
    evidence: 'withheld',
  },
  {
    id: 'wh-intake-live',
    area: 'Scheduling',
    publishable: false,
    withholdReason: 'recorded as unproven live',
    text: 'The intake page’s first live job and visit creation.',
    evidence: 'withheld',
  },
  {
    id: 'wh-outreach',
    area: 'Centaurus',
    publishable: false,
    withholdReason: 'the scheduler entry is written but not installed',
    text: 'The autonomous outreach engine as a shipped capability.',
    evidence: 'withheld',
  },
]

const INDEX = new Map(CLAIMS.map((c) => [c.id, c]))

/** Look a claim up by id. Withheld claims throw at build time in dev and are never rendered. */
export function P(id: string): Claim {
  const c = INDEX.get(id)
  if (!c) throw new Error(`Unknown proof id: ${id}`)
  if (!c.publishable) throw new Error(`Proof "${id}" is withheld: ${c.withholdReason ?? 'no reason given'}`)
  return c
}

export const WITHHELD_COUNT = CLAIMS.filter((c) => !c.publishable).length
