import {
    Database, Code2, ShieldCheck, FileText, GitBranch,
    AlertTriangle, Package, BarChart2, Repeat,
    Factory, Layers, CalendarClock, MonitorSmartphone, Server,
    ArrowLeftRight, Settings, DollarSign, BarChart, Cog,
    Brain, Map, Globe, Languages, Truck, Cpu,
    Zap, Eye, TrendingUp, Users, Lightbulb, Wrench,
    Target, LineChart, UserCheck, Rocket, PlaneTakeoff,
    BrainCircuit, Network, Shuffle, Boxes, Route, Landmark,
    FlaskConical, Send, Monitor,
} from 'lucide-react';
import type { SkillSection } from '../types';

export const SKILLS_HEADLINE = {
    eyebrow: 'Full Skill Profile',
    lead: 'Designed in systems.',
    highlight: 'Delivered as tools.',
    sub: 'Nearly 50 skills across systems design, tool building and operational leadership, built from real factories, real field crews, real pipelines and real production chaos.',
};

export const SKILL_SECTIONS: SkillSection[] = [
    {
        id: 'systems',
        label: '01',
        accent: 'sky',
        title: 'Systems Design & ERP Architecture',
        subtitle: 'Designing operational systems end to end: architecture, data models, costing, scheduling and migration strategy across Frappe/ERPNext, Business Central, Dynamics AX and MIL-SPEC production environments.',
        skills: [
            { icon: Boxes, title: 'Frappe / ERPNext Application Architecture', desc: 'A 68-page, 364-doctype custom app: mirror doctypes, whitelisted endpoints, permission maps, scheduler hooks, workspaces and desk pages, deployed on a single workstation behind nginx and a tunnel.' },
            { icon: Route, title: 'Field-Service Operations Design', desc: 'Dispatch boards, capacity engines, geo routing, time-off authority, plan-vs-actual calendars: the scheduling stack for ~70 technicians across service and construction work.' },
            { icon: Landmark, title: 'Construction Finance Systems', desc: 'AIA G703 schedules of values, progress billing with lien-waiver workflows, retention rules, borrowing-base certificates and cash-flow forecasting that back-tests against paid history.' },
            { icon: Factory, title: 'Manufacturing ERP Architecture', desc: 'End-to-end ERP design for Business Central v27+: architecture development, data transition and validation, production orders and planning worksheets.' },
            { icon: ArrowLeftRight, title: 'ERP Migration Strategy', desc: 'Legacy ERP to BC: a 750,000-item activity analysis, classification frameworks, cross-reference consolidation, go-live planning.' },
            { icon: Layers, title: 'Multi-Level BOM Design', desc: 'BOMs up to 7 levels deep with phantom assemblies, routing link codes, scrap factors, variant-level component selection and subcontracting.' },
            { icon: BarChart, title: 'Data Architecture & Analytics', desc: 'Custom table design for simulation and exception tracking, plus analytics on vendor quality, scrap trends and planning parameters.' },
            { icon: Settings, title: 'MRP & Supply Chain Config', desc: 'Reordering policies, safety stock, reorder points and lead-time management: demand-driven replenishment for items with 2-day to 4-month lead times.' },
            { icon: DollarSign, title: 'Standard Cost System Design', desc: 'Multi-level standard costing: material, direct labour from routing, setup amortisation, overhead, subcontracting, scrap allowances and variance analysis.' },
            { icon: MonitorSmartphone, title: 'Microsoft Dynamics 365 BC', desc: 'Deep functional expertise in BC v27+: production orders, planning worksheets, subcontracting, standard costing and item variants.' },
            { icon: Server, title: 'Dynamics AX', desc: 'Scale production planning in AX in an automotive Tier 1 environment.' },
            { icon: Cog, title: 'MIL-SPEC Connector Manufacturing', desc: 'Shell machining, outsourced plating with QC, contact hooding, insert assembly, epoxy potting and electrical testing per MIL-DTL-38999.' },
            { icon: Map, title: 'AutoCAD & Technical Drawing', desc: 'Reading and creating schematics for production planning and component design.' },
        ],
    },
    {
        id: 'tools',
        label: '02',
        accent: 'emerald',
        title: 'Tool Building: Python, Data & AI',
        subtitle: 'Writing the software that runs the systems: mirrors and refresh engines, planning boards, bots, AI agents with guardrails, and the test harnesses that prove they work.',
        skills: [
            { icon: Database, title: 'DuckDB Mirrors & Refresh Engines', desc: 'A 1.45M-row SaaS export mirrored into DuckDB and MariaDB with contract-driven transforms, schema-drift adoption and a zero-row-drift proof on every backup.' },
            { icon: BrainCircuit, title: 'LLM Tool-Calling with Guardrails', desc: 'Provider-swappable clients (Ollama, Anthropic), governed SQL tools, metric registries, fabrication guards and adversarial test suites. AI that answers from data or refuses.' },
            { icon: Send, title: 'Telegram Bot API Products', desc: 'Forum topics, pinned cards, inline keyboards with idempotent callbacks, long-polling services, DM hotlines and document handouts, designed around what the API actually permits.' },
            { icon: FlaskConical, title: 'Browser Automation & Runtime Tests', desc: 'Playwright export bots and screenshot pipelines; jsdom harnesses that execute a page\'s real JavaScript and caught three fatal-on-load bugs, three for three.' },
            { icon: Monitor, title: 'Front-Ends Without a Build Step', desc: 'Plotly, Leaflet, hand-rolled SVG physics and drag-and-drop boards in vanilla JS, including a 12,500-line planning core.' },
            { icon: Code2, title: 'Python Programming', desc: 'Multi-phase services, cron jobs, importers and reconciliation scripts built for repeatable production runs, not one-off cleanups.' },
            { icon: Database, title: 'Data Engineering & ETL', desc: 'Full extract → transform → load pipelines: reading raw messy exports, cleaning them and delivering structured, consumption-ready tables.' },
            { icon: Zap, title: 'Desktop Automation Agents', desc: 'PyAutoGUI, OCR and OpenCV combined into agents that drive legacy software no API has ever touched.' },
            { icon: Cpu, title: 'Local AI Infrastructure', desc: 'Pulled, ran and fine-tuned models like LLaMA 3.1 locally, deploying AI on private infrastructure, not just consuming APIs.' },
            { icon: Repeat, title: 'Reusable Process Automation', desc: 'Configuration-driven tools built for recurring runs, with dry-run defaults and an undo for every destructive script.' },
            { icon: ShieldCheck, title: 'Data Quality & Validation', desc: 'Tie-outs to the cent, byte-identical before/after hashes, counterfactual scripts. Measure, don\'t assert.' },
            { icon: FileText, title: 'Flat File & Encoding Expertise', desc: 'latin-1 vs utf-8-sig, delimiters, quoted fields with embedded commas, malformed rows: the unglamorous stuff done right.' },
            { icon: AlertTriangle, title: 'Edge Case Engineering', desc: 'Footer lines, names with commas, extra price-break columns: handling multiple failure modes inside a single pipeline.' },
            { icon: GitBranch, title: 'Business Logic → Code', desc: 'Translating domain rules (retention, sold-by, day-off categories, week bucketing) into one definition in one place.' },
            { icon: BarChart2, title: 'Reporting Integration', desc: 'Column engines with per-user layouts, spec-driven exports and print views that render the same DOM as the screen.' },
            { icon: Package, title: 'Supply Chain Data Mastery', desc: 'Part numbers, barcodes, price breaks, quantity tiers, lead times: inventory and catalog data for parts distribution.' },
        ],
    },
    {
        id: 'leadership',
        label: '03',
        accent: 'amber',
        title: 'Operations Leadership & Systems Thinking',
        subtitle: 'Bridging engineering, operations and AI, with international experience, bilingual communication and an ownership mindset.',
        skills: [
            { icon: Brain, title: 'Systems Thinker', desc: 'Management Engineering education trains the eye to see processes, constraints, optimisation logic and resource flows across the value chain.' },
            { icon: CalendarClock, title: 'Production Planning Specialist', desc: 'Managing 2,400+ order lines a month, inventory levels, material reservations, order forecasting and work-centre demand balancing.' },
            { icon: Target, title: 'Constraint-First Optimisation', desc: 'Constantly asking: where is delay created? What can be automated? What is the bottleneck? Theory of Constraints in daily practice.' },
            { icon: Users, title: 'Automotive Tier 1 Experience', desc: 'Tier 1 supplier environment for Audi, VW, Mercedes-Benz and BMW: just-in-time pressure and zero tolerance for delays.' },
            { icon: Globe, title: 'Global Manufacturing Operations', desc: 'Worked across Turkey, Bulgaria, Mexico and the United States: international adaptability and cross-cultural competence.' },
            { icon: Languages, title: 'Bilingual Operational Communicator', desc: 'Professional Spanish in production, logistics and field-crew environments.' },
            { icon: Truck, title: 'Logistics + Production Bridge', desc: 'Logistics controller background: customer demand visibility, delivery schedules, inventory positioning, transportation impact.' },
            { icon: TrendingUp, title: 'Data-Driven Planner', desc: 'Relying on demand patterns, historical data, lead times and capacity assumptions: structured logic, not intuition.' },
            { icon: Eye, title: 'Process Signal Architect', desc: 'Designing triggered signals inside workflows: automation triggers, intelligent alerts and proactive systems built for response.' },
            { icon: LineChart, title: 'Production Risk Analyst', desc: 'Sensitive to under-planning, overproduction, supply-chain delay and inventory cost: balancing risk across the planning horizon.' },
            { icon: UserCheck, title: 'Governance & Accountability', desc: 'Who changed what? Where are the audit rows? Governance maturity built into daily ERP operations.' },
            { icon: Wrench, title: 'ERP Customisation Strategist', desc: 'Never accepting out-of-the-box limits: designing systems that improve decision-making rather than conforming to defaults.' },
            { icon: Lightbulb, title: 'AI-Augmented Operations', desc: 'AI to read crew chat, describe jobsite photos, flag under-billed work and answer questions from the ledger. Human + AI collaboration, with the human deciding.' },
            { icon: Rocket, title: 'Entrepreneurial Ownership', desc: 'Thinking in terms of products, tooling and invention: an ownership mindset that goes beyond the job description.' },
            { icon: PlaneTakeoff, title: 'International Mobility', desc: 'Worked abroad, open to relocation, travels strategically.' },
            { icon: Network, title: 'Technical + Business Hybrid', desc: 'Sitting between engineering, operations, IT and business: a hybrid position that is extremely powerful in modern operations.' },
            { icon: Shuffle, title: 'Future Operations Stack', desc: 'Designing the convergence of ERP + AI + automation that defines the next generation of manufacturing and field service.' },
        ],
    },
];
